version: '3.5'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - './api:/usr/src/app'
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=development
    depends_on: 
      - mongo
  mongo: 
    image: mongo 
    volumes:
      - '../../../../data/db:/data/db'
    ports:
      - '27017:27017' 
  web:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on: 
      - api
      - frontend
